# Generated by Django 2.2 on 2019-04-23 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelBuddy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='plannedbys',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='travel_plans',
        ),
        migrations.AddField(
            model_name='trip',
            name='joins',
            field=models.ManyToManyField(related_name='joins', to='travelBuddy_app.Traveler'),
        ),
        migrations.AddField(
            model_name='trip',
            name='plannedby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plannedby', to='travelBuddy_app.Traveler'),
            preserve_default=False,
        ),
    ]
