# Generated by Django 2.2 on 2019-04-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelBuddy_app', '0002_auto_20190423_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='joins',
        ),
        migrations.AddField(
            model_name='trip',
            name='travel_plans',
            field=models.ManyToManyField(related_name='travel_plans', to='travelBuddy_app.Traveler'),
        ),
    ]
