# Generated by Django 2.2 on 2019-04-23 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelBuddy_app', '0003_auto_20190423_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='plannedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannedbys', to='travelBuddy_app.Traveler'),
        ),
    ]
